server:
  port: 6164
#database
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://containers-us-west-82.railway.app:7607/bankend
    username: postgres
    password: WLm3XHGe34szFAQQis6A
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
#router


#api binance



